# Create a copy of this file in the parent directory to use it.

services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - DATABASE_URL=postgresql://qpigeon:password@postgres:5432/qpigeon
    volumes:
      - ./instance/flask:/app/instance:rw
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: qpigeon
      POSTGRES_PASSWORD: password
      POSTGRES_DB: qpigeon
    ports:
      - 5432:5432
    volumes:
      - ./instance/postgres:/var/lib/postgresql/data:rw
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U qpigeon -d qpigeon"]
      interval: 5s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080