services:
  client:
    build:
      context: ../../
      dockerfile: docker/client/Dockerfile
    volumes:
      - ./instance:/root/.qpigeon:rw
    networks:
      - qpigeon
    command:
      - python
      - qpigeon/client/console.py
      - --endpoint
      - http://server-flask-1:5000
      - --profile
      - ~/.qpigeon/${QPIGEON_PROFILE}

networks:
  qpigeon:
    external: true